import { Network, Peer, LanGameBroadcast, SharedFile, DERPRelayNode } from './types';
import { generateWireGuardKey } from './utils/wireguard';

export const INITIAL_NETWORKS: Network[] = [
  {
    id: 'net-vwan-valheim',
    name: 'Valheim: Mistlands & Ashlands Co-Op',
    description: 'Public dedicated community co-op room. Join for boss progression and shared building.',
    subnetCidr: '10.147.19.0/24',
    gatewayIp: '10.147.19.1',
    listenPort: 51820,
    isPublic: true,
    hasPassword: false,
    inviteCode: 'VWAN-VALH-7721',
    gameCategory: 'Valheim',
    region: 'EU-Central',
    maxPeers: 64,
    ownerId: 'user-odin',
    ownerName: 'OdinHost_DE',
    createdAt: '2026-08-10T14:30:00Z',
    tags: ['Survival', 'Co-op', 'PVE', 'Europe', 'Low-Latency'],
    interfaceName: 'vwan0',
    isConnected: true,
    assignedVirtualIp: '10.147.19.4',
    clientPrivateKey: generateWireGuardKey(),
    clientPublicKey: generateWireGuardKey(),
    aclPreset: 'gaming-safe',
    aclRules: [
      {
        id: 'acl-1',
        name: 'Allow ICMP Ping',
        action: 'allow',
        protocol: 'icmp',
        source: 'any',
        destination: 'any',
        description: 'Permit latency diagnostics between peers'
      },
      {
        id: 'acl-2',
        name: 'Allow Game Port (Valheim 2456-2458)',
        action: 'allow',
        protocol: 'udp',
        portRange: '2456-2458',
        source: 'any',
        destination: 'any',
        description: 'Valheim peer-to-peer and server discovery'
      },
      {
        id: 'acl-3',
        name: 'Block Dangerous NetBIOS/SMB Ports',
        action: 'block',
        protocol: 'tcp',
        portRange: '139,445',
        source: 'any',
        destination: 'any',
        description: 'Protect peers against local Windows file protocol exploits'
      }
    ],
    bandwidthCapMbps: 0
  },
  {
    id: 'net-vwan-minecraft',
    name: 'Minecraft Java 1.20.4 - Hermitcraft-Style SMP',
    description: 'Whitelisted public SMP room. Voice chat mod supported via virtual subnet audio stream.',
    subnetCidr: '10.10.88.0/24',
    gatewayIp: '10.10.88.1',
    listenPort: 51822,
    isPublic: true,
    hasPassword: false,
    inviteCode: 'VWAN-MC88-9104',
    gameCategory: 'Minecraft',
    region: 'NA-East',
    maxPeers: 128,
    ownerId: 'user-redstone',
    ownerName: 'RedstoneWiz_US',
    createdAt: '2026-08-14T09:15:00Z',
    tags: ['SMP', 'Vanilla+', 'VoiceChat', 'US-East'],
    interfaceName: 'vwan1',
    isConnected: true,
    assignedVirtualIp: '10.10.88.12',
    clientPrivateKey: generateWireGuardKey(),
    clientPublicKey: generateWireGuardKey(),
    aclPreset: 'full-mesh',
    aclRules: [],
    bandwidthCapMbps: 0
  },
  {
    id: 'net-vwan-cs2',
    name: 'CS2 LAN 128-Tick Scrims & Retro Frag',
    description: 'Direct P2P low-jitter room for custom 5v5 competitive LAN server and surf maps.',
    subnetCidr: '10.200.1.0/24',
    gatewayIp: '10.200.1.1',
    listenPort: 51824,
    isPublic: true,
    hasPassword: false,
    inviteCode: 'VWAN-CS2-5512',
    gameCategory: 'Counter-Strike 2',
    region: 'EU-Central',
    maxPeers: 32,
    ownerId: 'user-clutch',
    ownerName: 'AeroStrike',
    createdAt: '2026-08-20T19:00:00Z',
    tags: ['Competitive', '128Tick', 'LowJitter', 'Scrims'],
    interfaceName: 'vwan2',
    isConnected: false,
    assignedVirtualIp: '10.200.1.8',
    clientPrivateKey: generateWireGuardKey(),
    clientPublicKey: generateWireGuardKey(),
    aclPreset: 'gaming-safe',
    aclRules: [],
    bandwidthCapMbps: 0
  },
  {
    id: 'net-vwan-palworld',
    name: 'Palworld 24/7 Dedicated Server Guild',
    description: 'High performance co-op server with custom breeding rates and dungeon expeditions.',
    subnetCidr: '10.50.0.0/24',
    gatewayIp: '10.50.0.1',
    listenPort: 51826,
    isPublic: true,
    hasPassword: false,
    inviteCode: 'VWAN-PALW-4390',
    gameCategory: 'Palworld',
    region: 'Asia-East',
    maxPeers: 64,
    ownerId: 'user-tamer',
    ownerName: 'PalMaster_Tokyo',
    createdAt: '2026-08-25T11:20:00Z',
    tags: ['Palworld', 'Survival', 'Asia', 'PVE'],
    interfaceName: 'vwan3',
    isConnected: false,
    assignedVirtualIp: '10.50.0.19',
    clientPrivateKey: generateWireGuardKey(),
    clientPublicKey: generateWireGuardKey(),
    aclPreset: 'full-mesh',
    aclRules: [],
    bandwidthCapMbps: 0
  },
  {
    id: 'net-vwan-homelab',
    name: 'Personal Dev Homelab & Remote SMB',
    description: 'Private encrypted VLAN connecting workstation, home TrueNAS storage, and cloud dev box.',
    subnetCidr: '10.220.10.0/24',
    gatewayIp: '10.220.10.1',
    listenPort: 51828,
    isPublic: false,
    hasPassword: true,
    inviteCode: 'VWAN-PRIV-9014',
    gameCategory: 'Remote Office',
    region: 'Global',
    maxPeers: 16,
    ownerId: 'self',
    ownerName: 'You (Host)',
    createdAt: '2026-09-01T08:00:00Z',
    tags: ['Private', 'SMB', 'SSH', 'Homelab', 'NAS'],
    interfaceName: 'vwan4',
    isConnected: false,
    assignedVirtualIp: '10.220.10.2',
    clientPrivateKey: generateWireGuardKey(),
    clientPublicKey: generateWireGuardKey(),
    aclPreset: 'host-only',
    aclRules: [],
    bandwidthCapMbps: 0
  }
];

export const MOCK_PEERS_BY_NETWORK: Record<string, Peer[]> = {
  'net-vwan-valheim': [
    {
      id: 'peer-self',
      name: 'Your-Laptop (This Device)',
      platform: 'windows',
      virtualIp: '10.147.19.4',
      publicKey: generateWireGuardKey(),
      endpoint: '192.168.1.105:51820',
      connectionMode: 'p2p',
      latencyMs: 1,
      txBytes: 1420500,
      rxBytes: 3890200,
      lastHandshake: '12 seconds ago',
      isSelf: true,
      status: 'online'
    },
    {
      id: 'peer-odin',
      name: 'OdinHost_DE [Dedicated Server]',
      platform: 'linux',
      virtualIp: '10.147.19.1',
      publicKey: generateWireGuardKey(),
      endpoint: '142.132.89.21:51820',
      connectionMode: 'p2p',
      latencyMs: 18,
      txBytes: 42100900,
      rxBytes: 89400200,
      lastHandshake: '4 seconds ago',
      isHost: true,
      status: 'online',
      sharedFolder: '\\\\10.147.19.1\\valheim_mods'
    },
    {
      id: 'peer-valk',
      name: 'ValkyrieWarrior-PC',
      platform: 'windows',
      virtualIp: '10.147.19.7',
      publicKey: generateWireGuardKey(),
      endpoint: '85.214.120.44:49811',
      connectionMode: 'p2p',
      latencyMs: 24,
      txBytes: 8500200,
      rxBytes: 12400500,
      lastHandshake: '18 seconds ago',
      status: 'online'
    },
    {
      id: 'peer-thor',
      name: 'ThorSteamDeck (Arch Linux)',
      platform: 'linux',
      virtualIp: '10.147.19.11',
      publicKey: generateWireGuardKey(),
      endpoint: 'relay-fra.vwan.net:443',
      connectionMode: 'relay',
      relayRegion: 'Frankfurt (DERP)',
      latencyMs: 42,
      txBytes: 3100400,
      rxBytes: 4900100,
      lastHandshake: '35 seconds ago',
      status: 'online'
    },
    {
      id: 'peer-freyja',
      name: 'Freyja-MacBookPro (macOS)',
      platform: 'macos',
      virtualIp: '10.147.19.15',
      publicKey: generateWireGuardKey(),
      endpoint: '78.46.90.11:51820',
      connectionMode: 'p2p',
      latencyMs: 31,
      txBytes: 2100800,
      rxBytes: 3450900,
      lastHandshake: '50 seconds ago',
      status: 'online'
    },
    {
      id: 'peer-heimdall',
      name: 'Heimdall_Pixel9 (Android 15)',
      platform: 'android',
      virtualIp: '10.147.19.22',
      publicKey: generateWireGuardKey(),
      endpoint: 'relay-fra.vwan.net:443',
      connectionMode: 'relay',
      relayRegion: 'Frankfurt (DERP)',
      latencyMs: 58,
      txBytes: 450100,
      rxBytes: 1200300,
      lastHandshake: '1 minute ago',
      status: 'idle'
    }
  ],
  'net-vwan-minecraft': [
    {
      id: 'peer-mc-self',
      name: 'Your-Laptop (This Device)',
      platform: 'windows',
      virtualIp: '10.10.88.12',
      publicKey: generateWireGuardKey(),
      endpoint: '192.168.1.105:51822',
      connectionMode: 'p2p',
      latencyMs: 1,
      txBytes: 2500000,
      rxBytes: 6800000,
      lastHandshake: '8 seconds ago',
      isSelf: true,
      status: 'online'
    },
    {
      id: 'peer-redstone-host',
      name: 'RedstoneWiz_US (Server Host)',
      platform: 'linux',
      virtualIp: '10.10.88.1',
      publicKey: generateWireGuardKey(),
      endpoint: '104.244.78.19:51822',
      connectionMode: 'p2p',
      latencyMs: 29,
      txBytes: 154000000,
      rxBytes: 320000000,
      lastHandshake: '3 seconds ago',
      isHost: true,
      status: 'online'
    },
    {
      id: 'peer-diamond-miner',
      name: 'Steve-Rig (Windows 11)',
      platform: 'windows',
      virtualIp: '10.10.88.5',
      publicKey: generateWireGuardKey(),
      endpoint: '24.19.201.88:51822',
      connectionMode: 'p2p',
      latencyMs: 34,
      txBytes: 12900000,
      rxBytes: 28000000,
      lastHandshake: '15 seconds ago',
      status: 'online'
    },
    {
      id: 'peer-creeper-hunter',
      name: 'CreeperHunter (iOS iPad)',
      platform: 'ios',
      virtualIp: '10.10.88.9',
      publicKey: generateWireGuardKey(),
      endpoint: 'relay-nyc.vwan.net:443',
      connectionMode: 'relay',
      relayRegion: 'New York (DERP)',
      latencyMs: 46,
      txBytes: 4200000,
      rxBytes: 11000000,
      lastHandshake: '22 seconds ago',
      status: 'online'
    }
  ],
  'net-vwan-cs2': [
    {
      id: 'peer-cs-host',
      name: 'AeroStrike [Dedicated CS2 128T]',
      platform: 'linux',
      virtualIp: '10.200.1.1',
      publicKey: generateWireGuardKey(),
      endpoint: '162.55.91.20:51824',
      connectionMode: 'p2p',
      latencyMs: 15,
      txBytes: 78000000,
      rxBytes: 92000000,
      lastHandshake: '2 seconds ago',
      isHost: true,
      status: 'online'
    },
    {
      id: 'peer-cs-player2',
      name: 'QuickScope99 (Win11)',
      platform: 'windows',
      virtualIp: '10.200.1.2',
      publicKey: generateWireGuardKey(),
      endpoint: '91.200.44.12:51824',
      connectionMode: 'p2p',
      latencyMs: 19,
      txBytes: 42000000,
      rxBytes: 51000000,
      lastHandshake: '5 seconds ago',
      status: 'online'
    }
  ]
};

export const INITIAL_LAN_GAMES: LanGameBroadcast[] = [
  {
    id: 'game-valheim-1',
    networkId: 'net-vwan-valheim',
    gameName: 'Valheim Dedicated Server',
    hostPeerName: 'OdinHost_DE',
    hostVirtualIp: '10.147.19.1',
    port: 2456,
    protocol: 'UDP',
    maxPlayers: 10,
    currentPlayers: 4,
    mapOrWorldName: 'Yggdrasil-Core',
    version: '0.218.15',
    startedAt: '3 hours ago'
  },
  {
    id: 'game-mc-1',
    networkId: 'net-vwan-minecraft',
    gameName: 'Minecraft Java SMP',
    hostPeerName: 'RedstoneWiz_US',
    hostVirtualIp: '10.10.88.1',
    port: 25565,
    protocol: 'TCP',
    maxPlayers: 20,
    currentPlayers: 6,
    mapOrWorldName: 'HermitLand-Season4',
    version: '1.20.4 Paper',
    startedAt: '12 hours ago'
  },
  {
    id: 'game-cs2-1',
    networkId: 'net-vwan-cs2',
    gameName: 'Counter-Strike 2 Custom LAN',
    hostPeerName: 'AeroStrike',
    hostVirtualIp: '10.200.1.1',
    port: 27015,
    protocol: 'UDP',
    maxPlayers: 10,
    currentPlayers: 8,
    mapOrWorldName: 'de_mirage',
    version: 'Latest (Source 2)',
    startedAt: '45 mins ago'
  }
];

export const INITIAL_SHARED_FILES: SharedFile[] = [
  {
    id: 'file-1',
    networkId: 'net-vwan-valheim',
    name: 'ValheimPlus-v0.9.9.11-ClientPatch.zip',
    sizeBytes: 18452000, // ~17.6 MB
    uploaderName: 'OdinHost_DE',
    uploaderVirtualIp: '10.147.19.1',
    uploadedAt: 'Yesterday, 18:22',
    sha256: '9f83acb4028d7a8e23f0011f58b093f4e240213b',
    mimeType: 'application/zip',
    category: 'game_mod',
    downloadCount: 14
  },
  {
    id: 'file-2',
    networkId: 'net-vwan-valheim',
    name: 'world_yggdrasil_backup_day420.db',
    sizeBytes: 94800000, // ~90.4 MB
    uploaderName: 'OdinHost_DE',
    uploaderVirtualIp: '10.147.19.1',
    uploadedAt: 'Today, 04:00',
    sha256: 'b337ef492091ea27c001a4f009cb7e19da401201',
    mimeType: 'application/octet-stream',
    category: 'save_file',
    downloadCount: 5
  },
  {
    id: 'file-3',
    networkId: 'net-vwan-valheim',
    name: 'bepinex_configuration_guide.pdf',
    sizeBytes: 2400000,
    uploaderName: 'Freyja-MacBookPro',
    uploaderVirtualIp: '10.147.19.15',
    uploadedAt: '2 days ago',
    sha256: 'e100f91a2bc4432098dca7119280eab5420138ff',
    mimeType: 'application/pdf',
    category: 'document',
    downloadCount: 9
  },
  {
    id: 'file-4',
    networkId: 'net-vwan-minecraft',
    name: 'SimpleVoiceChat-fabric-1.20.4-2.5.8.jar',
    sizeBytes: 4200000,
    uploaderName: 'RedstoneWiz_US',
    uploaderVirtualIp: '10.10.88.1',
    uploadedAt: '3 days ago',
    sha256: '55bcfa239019da82103fca00918237eab9001928',
    mimeType: 'application/java-archive',
    category: 'game_mod',
    downloadCount: 22
  }
];

export const DERP_RELAYS: DERPRelayNode[] = [
  {
    id: 'derp-fra',
    region: 'EU-Central',
    city: 'Frankfurt',
    country: 'Germany 🇩🇪',
    stunPort: 3478,
    derpPort: 443,
    latencyMs: 19,
    status: 'operational',
    currentRelaySessions: 1420
  },
  {
    id: 'derp-nyc',
    region: 'NA-East',
    city: 'New York',
    country: 'United States 🇺🇸',
    stunPort: 3478,
    derpPort: 443,
    latencyMs: 24,
    status: 'operational',
    currentRelaySessions: 2180
  },
  {
    id: 'derp-sfo',
    region: 'NA-West',
    city: 'San Francisco',
    country: 'United States 🇺🇸',
    stunPort: 3478,
    derpPort: 443,
    latencyMs: 41,
    status: 'operational',
    currentRelaySessions: 940
  },
  {
    id: 'derp-tyo',
    region: 'Asia-East',
    city: 'Tokyo',
    country: 'Japan 🇯🇵',
    stunPort: 3478,
    derpPort: 443,
    latencyMs: 52,
    status: 'operational',
    currentRelaySessions: 1120
  },
  {
    id: 'derp-sin',
    region: 'Asia-SE',
    city: 'Singapore',
    country: 'Singapore 🇸🇬',
    stunPort: 3478,
    derpPort: 443,
    latencyMs: 65,
    status: 'operational',
    currentRelaySessions: 810
  },
  {
    id: 'derp-sao',
    region: 'SA-East',
    city: 'São Paulo',
    country: 'Brazil 🇧🇷',
    stunPort: 3478,
    derpPort: 443,
    latencyMs: 88,
    status: 'operational',
    currentRelaySessions: 490
  }
];
